# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lastpage_pb2 as lastpage__pb2


class PS4StoreLastPageStub(object):
    """Defining the service 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastPage = channel.unary_unary(
                '/PS4StoreLastPage/GetLastPage',
                request_serializer=lastpage__pb2.LastPageRequest.SerializeToString,
                response_deserializer=lastpage__pb2.LastPageResponse.FromString,
                )


class PS4StoreLastPageServicer(object):
    """Defining the service 
    """

    def GetLastPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PS4StoreLastPageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastPage,
                    request_deserializer=lastpage__pb2.LastPageRequest.FromString,
                    response_serializer=lastpage__pb2.LastPageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PS4StoreLastPage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PS4StoreLastPage(object):
    """Defining the service 
    """

    @staticmethod
    def GetLastPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PS4StoreLastPage/GetLastPage',
            lastpage__pb2.LastPageRequest.SerializeToString,
            lastpage__pb2.LastPageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
